### PR TITLE
Build with SDK 2.15.19

### PR DESCRIPTION
**Pull request by oridool**
- Dependency on aws-secretsmanager-caching-java based on same SDK

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by dump247** [comment]
Is there any chance this will be merged or this library updated to sdk v2?

**Comment by rehevkor5** [comment]
@oridool IMO you should publish your version to Maven Central as its own artifact. I think people would be interested in using it directly.

**Comment by simonmarty** [comment]
Blocked by https://github.com/aws/aws-secretsmanager-caching-java/pull/13

**Comment by smobyrne** [comment]
Thanks for submitting this request. While we prioritize upgrading from SDK 1.x to 2.x, please share your use-case to move to 2.x which will help us understand your blocker and expedite the delivery of this feature.

**Comment by agedahl** [comment]
@smobyrne https://github.com/aws/aws-secretsmanager-jdbc/issues/105 means it's a blocker for us, using SDK 1.x will force us to downgrade from the current LTS version of java to java 11 and that's not an option.. Any chance of getting this expedited?

**Comment by drpacman** [comment]
Use case is disabling availability of IMDSv1 (see https://aws.amazon.com/blogs/security/defense-in-depth-open-firewalls-reverse-proxies-ssrf-vulnerabilities-ec2-instance-metadata-service/) which neccesitates moving off SDK 1.x

**Comment by simonmarty** [comment]
IMDSv2 is supported in SDK v1 as of https://github.com/aws/aws-sdk-java/commit/06a2180e

**Pull request closed without merging**
