### PR TITLE
Add AWSSecretsManagerSnowflakeDriver

### PR DESCRIPTION
**Pull request by dwilkolek**
*Issue #, if available:* 
https://github.com/aws/aws-secretsmanager-jdbc/issues/104

*Description of changes:* 
Added support for Snowflake driver.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by piotrkorlaga** [comment]
hey @goyalya why was it tagged with `wontfix`? This seems to be super helpful to merge.

**Comment by goyalya** [comment]
We are evaluating this request and we will revert here when we have more details.

**Comment by dwilkolek** [comment]
@jarbot Those PR changes work for me perfectly. Sadly they were not merged and I ended up building and publishing jar to internal artifactory

**Comment by dwilkolek** [comment]
Yes, I am connecting to snowflake and postgres at the same time - 2 JDBC datasources 🙂

**Pull request closed without merging**
